name: Build Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Укажите нужную версию Node.js

      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build

      - name: Archive production artifacts
        run: zip -r my-project-windows.zip build/

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build

      - name: Archive production artifacts
        run: zip -r my-project-macos.zip build/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build

      - name: Archive production artifacts
        run: zip -r my-project-linux.zip build/

  upload-artifacts:
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos, build-linux]
    steps:
      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-artifacts
          path: my-project-windows.zip

      - name: Upload macOS Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos-artifacts
          path: my-project-macos.zip

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-artifacts
          path: my-project-linux.zip