on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13]

    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: npm install

      - id: name
        run: echo "::set-output name=v::$(node -p "require('./package.json').version")"

      - uses: softprops/action-gh-release@v2.0.6      
        with:
          tag_name: v${{ steps.name.outputs.v }}
          name: ${{ steps.name.outputs.v }}
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}